export const GET_ALL_CONTACT = 'GET_ALL_CONTACT';
export const GET_ALL_CONTACT_SUCCESS = 'GET_ALL_CONTACT_SUCCESS';
export const GET_ALL_CONTACT_FAILED = 'GET_ALL_CONTACT_FAILED';
export const GET_ALL_CONTACT_RESET = 'GET_ALL_CONTACT_RESET';

export const GET_CONTACT_BY_ID = 'GET_CONTACT_BY_ID';
export const GET_CONTACT_BY_ID_SUCCESS = 'GET_CONTACT_BY_ID_SUCCESS';
export const GET_CONTACT_BY_ID_FAILED = 'GET_CONTACT_BY_ID_FAILED';
export const GET_CONTACT_BY_ID_RESET = 'GET_CONTACT_BY_ID_RESET';

export const SAVE_CONTACT = 'SAVE_CONTACT';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
export const SAVE_CONTACT_FAILED = 'SAVE_CONTACT_FAILED';
export const SAVE_CONTACT_RESET = 'SAVE_CONTACT_RESET';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';
export const UPDATE_CONTACT_RESET = 'UPDATE_CONTACT_RESET';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';
export const DELETE_CONTACT_RESET = 'DELETE_CONTACT_RESET';
